<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class MyController extends Controller
{
    private function isSuperAdminSession(): bool
    {
        $userId = session('id');
        if (!$userId) {
            return false;
        }

        $user = DB::table('users')->where('id', $userId)->first();
        return $user && in_array((int) $user->level_id, [5, 6], true);
    }

    // ------------------- GLOBAL SEARCH -------------------
    public function search(Request $request)
    {
        $q = $request->q;
        
        // Search Books
        $books = DB::table('books')
            ->whereNull('deleted_at')
            ->where('judul', 'like', "%$q%")
            ->get();
            
        // Search Users
        $users = DB::table('users')
            ->whereNull('deleted_at')
            ->where(function($query) use ($q) {
                $query->where('name', 'like', "%$q%")
                      ->orWhere('email', 'like', "%$q%");
            })
            ->get();
            
        // Search Loans
        $loans = DB::table('peminjaman_buku')
            ->join('books', 'peminjaman_buku.book_id', '=', 'books.id')
            ->join('users', 'peminjaman_buku.user_id', '=', 'users.id')
            ->select('peminjaman_buku.*', 'books.judul', 'users.name')
            ->whereNull('peminjaman_buku.deleted_at')
            ->where(function($query) use ($q) {
                $query->where('books.judul', 'like', "%$q%")
                      ->orWhere('users.name', 'like', "%$q%");
            })
            ->get();

        if ($request->ajax() || $request->wantsJson()) {
            return response()->json([
                'books' => $books,
                'users' => $users,
                'loans' => $loans,
                'count' => $books->count() + $users->count() + $loans->count()
            ]);
        }

        return view('search_results', compact('books', 'users', 'loans', 'q'));
    }

    // ------------------- SYSTEM MAINTENANCE -------------------
    public function maintenance()
    {
        // Only Super Admin
        $userId = session('id');
        $user = DB::table('users')->where('id', $userId)->first();
        if (!$user || ($user->level_id != 5 && $user->level_id != 6)) {
            return abort(403);
        }
        
        return view('system_maintenance');
    }

    public function backup()
    {
        // Only Super Admin
        $userId = session('id');
        $user = DB::table('users')->where('id', $userId)->first();
        if (!$user || ($user->level_id != 5 && $user->level_id != 6)) {
            return abort(403);
        }

        // Expanded MySQL Dump Logic
        $filename = 'backup-' . date('Y-m-d-H-i-s') . '.sql';
        
        // Get all tables dynamically
        $allTables = DB::select('SHOW TABLES');
        $tables = [];
        foreach ($allTables as $table) {
            foreach ($table as $key => $value) {
                $tables[] = $value;
            }
        }

        // Start constructing the content
        $content = "-- Backup Generated by Library System\n";
        $content .= "-- Date: " . now() . "\n";
        $content .= "-- --------------------------------------------------------\n\n";
        $content .= "SET FOREIGN_KEY_CHECKS=0;\n";
        $content .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n\n";
        
        foreach ($tables as $table) {
            // Get Create Table Syntax
            $createTable = DB::select("SHOW CREATE TABLE `$table`");
            $createTableSql = $createTable[0]->{'Create Table'};

            $content .= "-- Table structure for table `$table`\n";
            $content .= "DROP TABLE IF EXISTS `$table`;\n";
            $content .= $createTableSql . ";\n\n";

            // Get Data
            $rows = DB::table($table)->get();
            
            if ($rows->count() > 0) {
                $content .= "-- Dumping data for table `$table`\n";
                $content .= "INSERT INTO `$table` VALUES \n";
                
                $valuesArr = [];
                foreach ($rows as $row) {
                    $rowArray = (array)$row;
                    $rowValues = [];
                    foreach ($rowArray as $value) {
                        if ($value === null) {
                            $rowValues[] = "NULL";
                        } else {
                            $rowValues[] = "'" . addslashes($value) . "'";
                        }
                    }
                    $valuesArr[] = "(" . implode(', ', $rowValues) . ")";
                }
                
                $content .= implode(",\n", $valuesArr);
                $content .= ";\n\n";
            }
        }

        $content .= "SET FOREIGN_KEY_CHECKS=1;\n";

        return response()->streamDownload(function () use ($content) {
            echo $content;
        }, $filename);
    }

    public function resetDatabase()
    {
        // Only Super Admin
        $userId = session('id');
        $user = DB::table('users')->where('id', $userId)->first();
        if (!$user || !in_array((int) $user->level_id, [5, 6], true)) {
            return abort(403);
        }

        // Logic reset: truncate all tables and re-seed default data
        // WARNING: This is destructive
        
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        $tables = DB::select('SHOW TABLES');
        foreach ($tables as $table) {
            foreach ($table as $key => $value) {
                if ($value == 'levels' || $value == 'migrations') continue; // Don't wipe levels or migrations
                DB::table($value)->truncate();
            }
        }
        
        // Re-seed default Super Admin if needed, or redirect to login
        // For now, let's keep the current user as super admin
        DB::table('users')->insert([
            'name' => 'Super Admin',
            'email' => $user->email, // Keep current email
            'password' => $user->password, // Keep current password
            'level_id' => 6,
            'is_verified' => 1,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        return back()->with('success', 'Database has been reset to initial state.');
    }

    public function restoreDatabase(Request $request)
    {
        // Only Super Admin
        $userId = session('id');
        $user = DB::table('users')->where('id', $userId)->first();
        if (!$user || !in_array((int) $user->level_id, [5, 6], true)) {
            return abort(403);
        }

        $request->validate([
            'backup_file' => 'required|file|mimes:sql,txt'
        ]);

        try {
            $file = $request->file('backup_file');
            $sql = file_get_contents($file->getRealPath());

            // Split SQL by semicolon to execute commands individually if needed, 
            // or use DB::unprepared for raw execution
            
            // Note: DB::unprepared is risky if SQL source is untrusted, 
            // but here it's from Super Admin
            
            DB::unprepared($sql);

            return back()->with('success', 'Database restored successfully from backup.');
        } catch (\Exception $e) {
            return back()->with('error', 'Restore failed: ' . $e->getMessage());
        }
    }

    // ------------------- HOME / DASHBOARD -------------------
    public function home()
    {
        if (session('id') > 0) {
            $userId = session('id');
            $level = session('level');

            // --- PEMINJAM / MEMBER DASHBOARD ---
            if ($level == 3) {
                // Personal Stats
                $my_active_loans = DB::table('peminjaman_buku')
                    ->where('user_id', $userId)
                    ->where('status', 'dipinjam')
                    ->whereNull('deleted_at')
                    ->count();

                $my_total_loans = DB::table('peminjaman_buku')
                    ->where('user_id', $userId)
                    ->whereNull('deleted_at')
                    ->count();

                $my_returned_loans = DB::table('peminjaman_buku')
                    ->where('user_id', $userId)
                    ->where('status', 'dikembalikan')
                    ->whereNull('deleted_at')
                    ->count();

                // Personal Recent Activities
                $recent_activities = DB::table('peminjaman_buku')
                    ->join('books', 'peminjaman_buku.book_id', '=', 'books.id')
                    ->select('books.judul as book_title', 'peminjaman_buku.created_at', 'peminjaman_buku.status')
                    ->where('peminjaman_buku.user_id', $userId)
                    ->whereNull('peminjaman_buku.deleted_at')
                    ->orderBy('peminjaman_buku.created_at', 'desc')
                    ->limit(5)
                    ->get();
                
                // Personal Chart Data (Monthly)
                $monthly_loans = DB::table('peminjaman_buku')
                    ->select(DB::raw('COUNT(id) as count'), DB::raw('MONTH(tanggal_pinjam) as month'))
                    ->where('user_id', $userId)
                    ->whereYear('tanggal_pinjam', now()->year)
                    ->whereNull('deleted_at')
                    ->groupBy('month')
                    ->pluck('count', 'month')
                    ->toArray();
                
                $chart_data = array_fill(0, 12, 0);
                foreach ($monthly_loans as $month => $count) {
                    $chart_data[$month - 1] = $count;
                }

                return view('home', compact('my_active_loans', 'my_total_loans', 'my_returned_loans', 'recent_activities', 'chart_data'));
            } 
            
            // --- ADMIN / SUPER ADMIN DASHBOARD ---
            else {
                // Stats
                $total_books = DB::table('books')->whereNull('deleted_at')->count();
                $total_users = DB::table('users')->whereNull('deleted_at')->count();
                $active_loans = DB::table('peminjaman_buku')->where('status', 'dipinjam')->whereNull('deleted_at')->count();
                $today_loans = DB::table('peminjaman_buku')->whereDate('tanggal_pinjam', now())->whereNull('deleted_at')->count();

                // Recent Activities (Latest 5 loans globally)
                $recent_activities = DB::table('peminjaman_buku')
                    ->join('users', 'peminjaman_buku.user_id', '=', 'users.id')
                    ->join('books', 'peminjaman_buku.book_id', '=', 'books.id')
                    ->select('users.name as user_name', 'books.judul as book_title', 'peminjaman_buku.created_at', 'peminjaman_buku.status')
                    ->whereNull('peminjaman_buku.deleted_at')
                    ->orderBy('peminjaman_buku.created_at', 'desc')
                    ->limit(5)
                    ->get();

                // Chart Data (Monthly Loans Global)
                $monthly_loans = DB::table('peminjaman_buku')
                    ->select(DB::raw('COUNT(id) as count'), DB::raw('MONTH(tanggal_pinjam) as month'))
                    ->whereYear('tanggal_pinjam', now()->year)
                    ->whereNull('deleted_at')
                    ->groupBy('month')
                    ->pluck('count', 'month')
                    ->toArray();
                
                $chart_data = array_fill(0, 12, 0);
                foreach ($monthly_loans as $month => $count) {
                    $chart_data[$month - 1] = $count;
                }

                // Daily Loans Global (Last 7 Days)
                $daily_loans = DB::table('peminjaman_buku')
                    ->select(DB::raw('COUNT(id) as count'), DB::raw('DATE(tanggal_pinjam) as date'))
                    ->where('tanggal_pinjam', '>=', now()->subDays(7))
                    ->whereNull('deleted_at')
                    ->groupBy('date')
                    ->pluck('count', 'date')
                    ->toArray();

                $daily_data = [];
                $daily_labels = [];
                for ($i = 6; $i >= 0; $i--) {
                    $date = now()->subDays($i)->format('Y-m-d');
                    $daily_labels[] = now()->subDays($i)->format('D'); // Mon, Tue...
                    $daily_data[] = $daily_loans[$date] ?? 0;
                }

                // Top 3 Books (Most Borrowed)
                $top_books = DB::table('books')
                    ->select('books.judul', DB::raw('count(peminjaman_buku.id) as total_pinjam'))
                    ->join('peminjaman_buku', 'books.id', '=', 'peminjaman_buku.book_id')
                    ->whereNull('books.deleted_at')
                    ->groupBy('books.id', 'books.judul')
                    ->orderByDesc('total_pinjam')
                    ->limit(3)
                    ->get();

                $top_book_labels = $top_books->pluck('judul')->toArray();
                $top_book_data = $top_books->pluck('total_pinjam')->toArray();

                return view('home', compact('total_books', 'total_users', 'active_loans', 'today_loans', 'recent_activities', 'chart_data', 'daily_data', 'daily_labels', 'top_book_labels', 'top_book_data'));
            }
        } else {
            return redirect('/login');
        }
    }

    // ------------------- TRASH (SUPER ADMIN) -------------------
    public function trash()
    {
        // Only Super Admin
        $userId = session('id');
        $user = DB::table('users')->where('id', $userId)->first();
        if (!$user || ($user->level_id != 5 && $user->level_id != 6)) {
            return abort(403);
        }

        $deletedBooks = DB::table('books')->whereNotNull('deleted_at')->get();
        $deletedUsers = DB::table('users')->whereNotNull('deleted_at')->get();
        $deletedLoans = DB::table('peminjaman_buku')
            ->join('books', 'peminjaman_buku.book_id', '=', 'books.id')
            ->join('users', 'peminjaman_buku.user_id', '=', 'users.id')
            ->select('peminjaman_buku.*', 'books.judul', 'users.name')
            ->whereNotNull('peminjaman_buku.deleted_at')
            ->get();
        $deletedIncoming = DB::table('data_masuk_buku')
            ->join('books', 'data_masuk_buku.book_id', '=', 'books.id')
            ->select('data_masuk_buku.*', 'books.judul')
            ->whereNotNull('data_masuk_buku.deleted_at')
            ->get();

        return view('trash', compact('deletedBooks', 'deletedUsers', 'deletedLoans', 'deletedIncoming'));
    }

    public function revertEdit($id)
    {
        if (!$this->isSuperAdminSession()) return view('404');

        $history = DB::table('edit_histories')->where('id', $id)->first();
        if (!$history || !$history->old_values) {
            return back()->with('error', 'Data riwayat tidak dapat direvert.');
        }

        $oldValues = json_decode($history->old_values, true);
        if (!$oldValues || !is_array($oldValues)) {
            return back()->with('error', 'Data lama tidak tersedia.');
        }

        $table = $history->table_name;
        $rowId = $history->row_id;

        if (!in_array($table, ['books', 'data_masuk_buku', 'peminjaman_buku', 'users'])) {
            return back()->with('error', 'Tabel tidak didukung untuk revert.');
        }

        $current = DB::table($table)->where('id', $rowId)->first();
        if (!$current) {
            return back()->with('error', 'Data sumber tidak ditemukan.');
        }

        $currentArray = [];
        foreach ($oldValues as $key => $value) {
            if (property_exists($current, $key)) {
                $currentArray[$key] = $current->$key;
            }
        }

        $beforeValues = $currentArray;
        $afterValues = $oldValues;

        $perubahanText = 'Revert ke versi sebelumnya';
        $detailChanges = [];

        foreach ($afterValues as $key => $afterVal) {
            $beforeVal = array_key_exists($key, $beforeValues) ? $beforeValues[$key] : null;
            if ((string)$beforeVal === (string)$afterVal) {
                continue;
            }

            // Simple label mapping
            $label = ucfirst($key);
            $beforeText = $beforeVal === null || $beforeVal === '' ? '-' : (string)$beforeVal;
            $afterText = $afterVal === null || $afterVal === '' ? '-' : (string)$afterVal;
            $detailChanges[] = $label . ': ' . $beforeText . ' → ' . $afterText;
        }

        if (!empty($detailChanges)) {
            $perubahanText = 'Revert: ' . implode('; ', $detailChanges);
        } else {
            $perubahanText = 'Revert ke versi sebelumnya (tanpa perubahan nilai)';
        }

        DB::table($table)->where('id', $rowId)->update($oldValues);

        DB::table('edit_histories')->insert([
            'table_name' => $table,
            'row_id' => $rowId,
            'perubahan' => $perubahanText,
            'old_values' => json_encode($beforeValues),
            'new_values' => json_encode($afterValues),
            'edited_by' => session('id'),
            'created_at' => now(),
            'updated_at' => now()
        ]);

        return back()->with('success', 'Data berhasil dikembalikan ke versi sebelumnya.');
    }

    public function restore($type, $id)
    {
        if (!$this->isSuperAdminSession()) return view('404');

        $table = '';
        if ($type == 'book') $table = 'books';
        elseif ($type == 'user') $table = 'users';
        elseif ($type == 'peminjaman') $table = 'peminjaman_buku';
        elseif ($type == 'datamasuk') $table = 'data_masuk_buku';

        if ($table) {
            DB::table($table)->where('id', $id)->update(['deleted_at' => null]);
            return back()->with('success', 'Data berhasil dikembalikan!');
        }
        return back()->with('error', 'Tipe data tidak valid');
    }

    public function forceDelete($type, $id)
    {
        if (!$this->isSuperAdminSession()) return view('404');

        $table = '';
        if ($type == 'book') $table = 'books';
        elseif ($type == 'user') $table = 'users';
        elseif ($type == 'peminjaman') $table = 'peminjaman_buku';
        elseif ($type == 'datamasuk') $table = 'data_masuk_buku';

        if ($table) {
            DB::table($table)->where('id', $id)->delete();
            // If user, also delete related
            if ($type == 'user') {
                DB::table('penjagas')->where('user_id', $id)->delete();
                DB::table('peminjams')->where('user_id', $id)->delete();
            }
            return back()->with('success', 'Data dihapus permanen!');
        }
        return back()->with('error', 'Tipe data tidak valid');
    }

    public function restoreAll($type)
    {
        if (!$this->isSuperAdminSession()) return view('404');

        $table = '';
        if ($type == 'book') $table = 'books';
        elseif ($type == 'user') $table = 'users';
        elseif ($type == 'peminjaman') $table = 'peminjaman_buku';
        elseif ($type == 'datamasuk') $table = 'data_masuk_buku';

        if ($table) {
            DB::table($table)->whereNotNull('deleted_at')->update(['deleted_at' => null]);
            return back()->with('success', 'Semua data tipe ' . $type . ' berhasil dikembalikan!');
        }
        return back()->with('error', 'Tipe data tidak valid');
    }

    // ------------------- USER PROFILE -------------------
    public function profile()
    {
        if (session('id') > 0) {
            $user = DB::table('users')->where('id', session('id'))->first();
            return view('profile', compact('user'));
        } else {
            return redirect('/login');
        }
    }

    public function updateProfile(Request $request)
    {
        if (session('id') > 0) {
            $id = session('id');
            
            $request->validate([
                'name' => 'required|string|max:255',
                'email' => 'required|email|unique:users,email,' . $id,
                'whatsapp' => 'nullable|string|max:20',
                'password' => 'nullable|min:6|confirmed'
            ]);

            $data = [
                'name' => $request->name,
                'email' => $request->email,
                'whatsapp' => $request->whatsapp,
                'updated_at' => now()
            ];

            if ($request->filled('password')) {
                $data['password'] = \Illuminate\Support\Facades\Hash::make($request->password);
            }

            DB::table('users')->where('id', $id)->update($data);

            // Update session name if changed
            Session::put('name', $request->name);

            return back()->with('success', 'Profil berhasil diperbarui!');
        } else {
            return redirect('/login');
        }
    }
}
